complited
Flash-Kaa/Java-Course-Tinkoff pull request #6
Opened 2023-10-29 07:49 UTC by Flash-Kaa

2023-11-12 21:50 UTC, VictorMinsky requested changes

2023-11-12 21:50 UTC, VictorMinsky commented on src/main/java/edu/hw4/task1/Task1.java
> +    public static List<Animal> sortByHeight(List<Animal> animals) {
Было бы неплохо писать в комментах к функции номер и условие задания

2023-11-12 21:50 UTC, VictorMinsky commented on src/main/java/edu/hw4/task1/Task1.java
В этом задании можно и было бы удобнее сделать всё в одном файле, т.к. по факту все функции относятся к одному и тому же классу (рекорду). Когда задания действительно никак не зависят друг от друга, тогда мы их и разносим в разные пакеты

2023-11-12 21:50 UTC, VictorMinsky commented on src/main/java/edu/hw4/task1/Task1.java
Ох, я запуллил, а ты ещё оказывается их и в отдельный пакет положил)

2023-11-12 21:50 UTC, VictorMinsky commented on src/main/java/edu/hw4/task3/Task3.java
> +        return map;
Перепиши на стримы. В помощь `Collectors.groupingBy`, `Collectors.collectingAndThen`

2023-11-12 21:50 UTC, VictorMinsky commented on src/main/java/edu/hw4/task4/Task4.java
> +        return animals.stream().max(Comparator.comparing(Animal::name)).get();
Операции в стримах обычно пишут с новой строки

2023-11-12 21:50 UTC, VictorMinsky commented on src/main/java/edu/hw4/task5/Task5.java
> +        }
Перепиши на стримы. В помощь `filter`, `count`

2023-11-12 21:50 UTC, VictorMinsky commented on src/main/java/edu/hw4/task6/Task6.java
> +            (a, b) -> a.weight() > b.weight() ? a : b
`BinaryOperator.maxBy`

2023-11-12 21:50 UTC, VictorMinsky commented on src/main/java/edu/hw4/task20/Task20.java
> +                    .split(" ")[0]
`\\s+`

2023-11-13 05:03 UTC, Flash-Kaa commented on src/main/java/edu/hw4/task1/Task1.java
Насчёт отдельных заданий: в курсе сказано, что каждое задание надо выполнять в своём классе
Насчёт пакетов: вы сами сказали разбивать все задания на пакеты..

2023-11-13 05:05 UTC, Flash-Kaa commented on src/main/java/edu/hw4/task5/Task5.java
> +        }
Разве моя версия не более оптимизирована по времеи? И по памяти вроде тоже..

2023-11-13 06:16 UTC, VictorMinsky commented on src/main/java/edu/hw4/task5/Task5.java
> +        }
Да, но задание на стримы, поэтому используем их)

2023-11-13 06:18 UTC, VictorMinsky commented on src/main/java/edu/hw4/task1/Task1.java
Да, так и надо делать. Здесь просто видишь, много мелких заданий на одно и то же. В принципе имело смысл делать чисто в одном файле. Можешь не трогать структуру и оставить как есть

2023-11-13 13:18 UTC, VictorMinsky commented on src/main/java/edu/hw4/task1/Task1.java
> +    public static List<Animal> sortByHeight(List<Animal> animals) {
Норм, ещё бы номер задания)

2023-11-13 13:20 UTC, VictorMinsky approved these changes
OK

2023-11-13 13:24 UTC, Flash-Kaa commented on src/main/java/edu/hw4/task20/Task20.java
> +                    .split(" ")[0]
fixed

2023-11-13 13:24 UTC, Flash-Kaa commented on src/main/java/edu/hw4/task6/Task6.java
> +            (a, b) -> a.weight() > b.weight() ? a : b
fixed

2023-11-13 13:24 UTC, Flash-Kaa commented on src/main/java/edu/hw4/task5/Task5.java
> +        }
fixed

2023-11-13 13:25 UTC, Flash-Kaa commented on src/main/java/edu/hw4/task4/Task4.java
> +        return animals.stream().max(Comparator.comparing(Animal::name)).get();
fixed

2023-11-13 13:25 UTC, Flash-Kaa commented on src/main/java/edu/hw4/task3/Task3.java
> +        return map;
fixed

2023-11-13 13:25 UTC, Flash-Kaa commented on src/main/java/edu/hw4/task1/Task1.java
Понял, спасибо

2023-11-13 13:27 UTC, Flash-Kaa commented on src/main/java/edu/hw4/task1/Task1.java
> +    public static List<Animal> sortByHeight(List<Animal> animals) {
Но у меня и так по заданиям разбито. Масло масляное выйдет же
В следующих дз буду прописывать условия и номера

2023-11-13 13:27 UTC, merged

2023-11-13 13:47 UTC, VictorMinsky commented on src/main/java/edu/hw4/task1/Task1.java
> +    public static List<Animal> sortByHeight(List<Animal> animals) {
Я пока не видел следующее, но если там именно реализуйте что-то или что-то более комплексное, то не надо. Тут видишь, домашка больше на потренировать стримы и всё, каждый номер -- одна мини-функция, поэтому условия писали. В следующих так делать не надо)